//! Account creation and modification capability.
//!
//! Separate from [`super::accounts::AccountReader`] because the two have
//! different risk profiles and different implementations: reading the passwd
//! database is unprivileged and universal, while creating an account, granting
//! it administrative rights or locking one out are privileged operations whose
//! commands differ by what the distribution ships.
//!
//! The administrative group is the divergence that motivates the capability:
//! Debian grants sudo through `sudo`, Arch and RHEL through `wheel`. Adding a
//! user to a group that does not exist is the failure mode to guard against —
//! `usermod -aG sudo` on Arch exits zero and grants nothing.

use crate::error::Result;
use crate::exec::Executor;

/// How an account's password is set up when it is created.
///
/// Not `Copy`, unlike its neighbours here: [`Self::Set`] carries a secret, and
/// a type that copies itself implicitly is one whose copies nobody counted.
///
/// `Debug` is written out below rather than derived, for the same reason.
#[derive(Clone, PartialEq, Eq)]
pub enum PasswordPolicy {
    /// No password is set, so password authentication cannot succeed.
    ///
    /// Safe only alongside a sudo rule that does not ask for one: an account
    /// with no password and a sudo rule that prompts for it can never
    /// authenticate, which is a broken administrator rather than a hardened
    /// one.
    Locked,
    /// The given password is set on the account.
    ///
    /// Applied with `chpasswd`, which reads `user:password` from stdin.
    /// **Never `useradd -p`**: that takes the value as an argument, and an
    /// argument is readable by every account on the box through
    /// `/proc/<pid>/cmdline` for as long as the process lives. It also expects
    /// an already-computed hash, which would oblige this tool to implement
    /// crypt itself.
    ///
    /// The value is in this process, which the rest of the design avoids —
    /// `sudo` is handed the terminal so it can prompt, and a WireGuard key is
    /// generated by `wg` and piped without being read here. Accepted for this
    /// one value deliberately: the alternative was `passwd` on the terminal,
    /// which cannot be optional without a second field asking whether to run
    /// it, and that field asked an operator to type "yes" to answer a question
    /// with two answers.
    ///
    /// What is still guaranteed: it never reaches `argv`, never reaches the
    /// output pane, and never appears in an error — `Command`'s `Display`
    /// omits stdin for exactly this reason.
    Set(String),
}

impl std::fmt::Debug for PasswordPolicy {
    /// Names the variant and never the password.
    ///
    /// Written out rather than derived because the derive prints the `String`.
    /// Nothing formats this type today, which is the argument for doing it now
    /// rather than the argument against: the leak would arrive with an
    /// unrelated `{:?}` in a panic message or a log line somebody adds while
    /// debugging something else, and it would not look like a change to how
    /// passwords are handled.
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Locked => f.write_str("Locked"),
            Self::Set(_) => f.write_str("Set(<redacted>)"),
        }
    }
}

/// How an account is barred from logging in.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum LockMethod {
    /// Expire the account, which refuses every authentication method.
    ///
    /// The important one, and the reason this is an enum rather than a single
    /// `lock` call. A `!`-prefixed password hash — what `passwd -l` writes —
    /// is checked by PAM's auth phase, and public-key authentication never
    /// reaches that phase: `sshd` reads `authorized_keys` and never calls
    /// `pam_authenticate`. So on a PAM build, a locked password leaves
    /// key-based login working — the opposite of what locking is asked for.
    ///
    /// OpenSSH does carry its own `platform_locked_account()` check, but it is
    /// compiled behind `!options.use_pam`. Whether it runs is therefore a
    /// property of how the distribution *built* OpenSSH, not of its
    /// configuration:
    ///
    /// - Debian and Arch build with PAM. `UsePAM yes` is the default, the
    ///   check is compiled out, and a `!` hash admits a key.
    /// - Alpine builds without it. `UsePAM` is not even a directive its `sshd
    ///   -T` recognises, the check runs, and a `!` hash refuses every method —
    ///   verified in a container, where an account created by `adduser -D` was
    ///   refused with "account is locked" despite holding a valid key.
    ///
    /// Expiry is used regardless, because it is the only mechanism that means
    /// the same thing on all three: it lives in a different shadow field and
    /// is honoured whatever OpenSSH was built against.
    Expire,
}

/// Creates and modifies accounts on the administered system.
pub trait AccountWriter {
    /// Creates an account with a home directory and a login shell.
    fn create(
        &self,
        executor: &dyn Executor,
        user: &str,
        shell: &str,
        password: PasswordPolicy,
    ) -> Result<()>;

    /// Adds an account to a supplementary group.
    ///
    /// Fails when the group does not exist rather than reporting success:
    /// `usermod -aG` is happy to be told about a group the system has never
    /// heard of, and the account silently gains nothing.
    fn add_to_group(&self, executor: &dyn Executor, user: &str, group: &str) -> Result<()>;

    /// Whether a group exists.
    fn group_exists(&self, executor: &dyn Executor, group: &str) -> Result<bool>;

    /// Whether an account is a member of a group.
    fn is_in_group(&self, executor: &dyn Executor, user: &str, group: &str) -> Result<bool>;

    /// Changes an account's login shell.
    ///
    /// The shell must already be listed in `/etc/shells`; a shell absent from
    /// it is refused by `chsh` and, on some systems, by services that consult
    /// the list before granting a session.
    fn set_shell(&self, executor: &dyn Executor, user: &str, shell: &str) -> Result<()>;

    /// Deletes an account.
    ///
    /// `remove_home` is a parameter rather than a policy because both answers
    /// are defensible and neither is safe as a default nobody stated: a home
    /// holding dotfiles is residue, and one holding a year of someone's work is
    /// not something an interface should decide about. Callers are expected to
    /// default to keeping it and to name the path *and its size* when offering
    /// the other answer — "delete /home/deploy (2.4 GB)" is a decision an
    /// operator can make, "also delete the home directory?" is not.
    ///
    /// The one operation here that destroys data this tool never created,
    /// which is why the parameter exists at all rather than the method simply
    /// doing the thorough thing.
    fn delete(&self, executor: &dyn Executor, user: &str, remove_home: bool) -> Result<()>;

    /// Bars an account from logging in by any method.
    fn lock(&self, executor: &dyn Executor, user: &str, method: LockMethod) -> Result<()>;

    /// Lifts what [`lock`](Self::lock) put in place.
    ///
    /// Takes the method rather than guessing, so it undoes what was done: the
    /// two mechanisms live in different shadow fields, and clearing the wrong
    /// one reports success over an account that is still barred.
    ///
    /// What it restores is the *ability* to authenticate, never a credential.
    /// An expiry lifted from an account holding no usable password leaves it
    /// exactly as unusable as before — which is why the task above this refuses
    /// to imply otherwise, and why nothing here writes a password.
    fn unlock(&self, executor: &dyn Executor, user: &str, method: LockMethod) -> Result<()>;

    /// Whether an account is barred from logging in.
    fn is_locked(&self, executor: &dyn Executor, user: &str) -> Result<bool>;

    /// Whether an account holds a password that can authenticate.
    ///
    /// Asked because a password is a way into the machine that
    /// `authorized_keys` cannot see, and the two are not interchangeable:
    /// `users.lock-root` expires root through PAM, which bars *every* channel
    /// including the provider's rescue console, so what has to be established
    /// beforehand is that some account can still get in by *some* means. A
    /// guard that only looked for a key refused an administrator whose
    /// distribution installer had set a password — the common case on a
    /// provider image, and one where the console is the way back in.
    ///
    /// True only for a hash that can actually match. The shadow field carries
    /// three states that are not a password: empty (no password at all, so
    /// PAM's `nullok` decides and it is absent by default on all five
    /// families), and `!` or `*` prefixes, which cannot be produced by any
    /// input because neither is in the crypt alphabet — `!` is what `passwd
    /// -l` writes and `*` is what a system account carries.
    fn has_password(&self, executor: &dyn Executor, user: &str) -> Result<bool>;

    /// The login shells the system will accept.
    ///
    /// Read rather than assumed: `/usr/bin/fish` and `/bin/fish` are both real
    /// locations depending on the distribution, and offering one the system
    /// does not list produces an account that cannot log in.
    fn valid_shells(&self, executor: &dyn Executor) -> Result<Vec<String>>;
}
